home/urls.py
from django.urls import path, include


from . import views
from rest_framework import routers

app_name = 'home'
rr = routers.DefaultRouter()
rr.register('', views.orderitem)

rrr = routers.DefaultRouter()
rrr.register('', views.order)


r = routers.DefaultRouter()
r.register('', views.product)

urlpatterns = [
    path('ca/', views.cart, name='cart'),
    path('Category/', views.Category_listAPI, name='category'),
    path('Category/<int:id>', views.Category_detail, name='category_detail'),

    path('Category/list/', views.Categories_listAPI, name='category'),
    path('Categories/<int:id>', views.Categories_detail, name='category_detail'),

    path('', views.product_listAPI, name='product_list'),
    path('product/<int:id>', views.product_detail, name='product_detail'),

    path('cart/', views.Order_list, name='shopping_cart'),
    path('order/', include(rrr.urls)),
    path('itemorder/', include(rr.urls)),
    path('Recommended/', views.Recommended_listAPI, name='Recommended'),
    path('productAPI/', include(r.urls)),
    path('addcart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('removecart/<int:product_id>/', views.remove_cart, name='remove_cart'),
    path('removecart_item/<int:product_id>/',
         views.remove_cart_item, name='remove_cart_item'),



]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('authentications.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('users/', include('authentications.urls')),
    path('verification/', include('verify_email.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
]

home/models.py
from django.db import models
from authentications.models import User
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from pickle import TRUE
# from home.content_based import ContentBasedRecommender
from django.utils.text import slugify
# from modeltranslation.translation import addtranslations
# Create your models here.


class Product(models.Model):
    id = models.AutoField(primary_key=True, name="product_id")
    Name = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, null=True)
    price = models.DecimalField(max_digits=20, decimal_places=0, null=True)
    Production_country = models.CharField(max_length=50)
    image = models.ImageField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.Name)
    #     super(Product, self).save(*args,**kwargs)

    def __str__(self):
        return self.Name


class Category(models.Model):
    id = models.AutoField(primary_key=True, name="category_id")
    Name = models.CharField(max_length=25)
    category_products = models.ManyToManyField(
        "Product", related_name="categories")

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        # translatable_fields = ("Name", "category_products")

    def __str__(self):
        return self.Name


class Recommended(models.Model):
    id = models.AutoField(primary_key=True, name="recommend_id")
    product_name = models.ForeignKey("Product", on_delete=models.CASCADE)
    recomended_devices = models.ManyToManyField("Product", related_name="aa")

    def __str__(self):
        return str(self.product_name)

# @receiver(post_save, sender=Product)
# def recommend(sender, **kwargs):
#     reco = Product.objects.all().values().last()
#     x = ContentBasedRecommender()

#     recommendation = x.get_recommendation(reco['product_id'])

#     reco_model = Recommended()

#     reco_model.product_name_id = reco['product_id']
#     reco_model.recommend_id = reco['product_id']

#     reco_model.recomended_devices.set(recommendation)
#     reco_model.save(force_insert=True)


@receiver(post_save, sender=Product)
def recommend(sender, **kwargs):
    reco = Product.objects.all().values().last()
    x = ContentBasedRecommender()
    recommendation = x.get_recommendation(reco['product_id'])
    if recommendation != 0:
        reco_model = Recommended()

        reco_model.product_name_id = reco['product_id']
        reco_model.recommend_id = reco['product_id']

        reco_model.recomended_devices.set(recommendation)
        reco_model.save(force_insert=True)


class OrderItem(models.Model):
    id = models.AutoField(primary_key=True, name="orderitem_id")
    item = models.ForeignKey("Product", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.user.email) + " " + str(self.item.Name)

    def get_cost(self):
        return self.price * self.quantity


class Order(models.Model):

    id = models.AutoField(primary_key=True, name="order_id")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    order_list = models.TextField()
    total_price = models.FloatField(default=0)
    status = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user.email) + " " + str(self.total_price)

# @receiver(pre_save, sender=OrderItem)
# def correct_price(sender, **kwargs):
#     cart_items = kwargs['instance']
#     price_of_product = Product.objects.get(product_id=cart_items.item.product_id)
#     cart_items.price = cart_items.quantity * float(price_of_product.price)
#     total_cart_items = OrderItem.objects.filter(user = cart_items.user )
#     # cart = Order.objects.get(order_id = cart_items.cart.order_id)
#     cart=Order.objects.create(user_id=cart_items.user.id)
#     cart.total_price = cart_items.price
#     multiplier = 10 / 100
#     cart.profit = (cart.total_price * multiplier)
#     cart.save()


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.Name

    def sub_total(self):
        return self.product.price * self.quantity


# addtranslations(__name__)

home/views.py
from .models import Product, Category, OrderItem, Order, Recommended, Cart, CartItem
from .serializers import HomeSerializers, CategorySerializers, RecommendedSerializers, jsonOrder, jsonOrderItem, ProductFilter
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import viewsets
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.http import request
from rest_framework.views import APIView
from django.core.paginator import Paginator
from .filters import ProductFilter
from rest_framework import generics
from django_filters import rest_framework as filters
from django.http import HttpResponse
# from authentications.models import User


# @api_view(['Post','GET'])
# def Home_listAPI(request):
#     all_ads=Products.objects.all()
#     permission_classes = [permissions.IsAdminUser]
#     return Response(HomeSerializers(all_ads,many=True).data)


@api_view(['GET', 'Post'])
def Recommended_listAPI(request):
    all_ads = Recommended.objects.all().distinct()
    # permission_classes = [permissions.IsAdminUser]
    return Response(RecommendedSerializers(all_ads, many=True).data)


class product(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = HomeSerializers
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ProductFilter


# @api_view(['GET', 'Post'])
@login_required
def product_listAPI(request):
    all_ads = Product.objects.all()
    product_filter = ProductFilter(request.GET, queryset=all_ads)
    all_ads = product_filter.qs

    paginator = Paginator(all_ads, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'products': page_obj,
               'product_filter': product_filter, 'all_products': all_ads}
    return render(request, 'home/product_list.html', context)
    # return Response(CategorySerializers(all_ads,many=True).data)


def product_detail(request, id):
    all_ads = Product.objects.get(product_id=id)
    context = {'product': all_ads}
    return render(request, 'home/product_detail.html', context)


@api_view(['GET', 'Post'])
def Categories_listAPI(request):
    all_ads = Category.objects.all()
    context = {'categories': all_ads}
    return render(request, 'home/category_list.html', context)


def Categories_detail(request, id):
    all_ads = Category.objects.get(category_id=id)
    catts = all_ads.category_products.all()
    context = {'category': all_ads,
               'catts': catts}
    return render(request, 'home/category_detail.html', context)


@api_view(['GET', 'Post'])
def Category_listAPI(request):
    all_ads = Category.objects.all()
    # context={'categories':all_ads}
    # return render(request,'home/category_list.html',context)
    return Response(CategorySerializers(all_ads, many=True).data)


# REST API
@api_view(['GET'])
def Category_detail(request, id):
    all_ads = Category.objects.get(category_id=id)
    return Response(CategorySerializers(all_ads).data)


class orderitem(viewsets.ModelViewSet):
    queryset = OrderItem.objects.all()
    serializer_class = jsonOrderItem


class order(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = jsonOrder


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(product_id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
    cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('home:cart')


def remove_cart(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, product_id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('home:cart')


def remove_cart_item(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, product_id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('home:cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
    except:
        pass
    context = {
        "cart_items": cart_items,
        "total": total,
        "quantity": quantity,
    }

    return render(request, 'home/cart.html', context)


def Order_list(request):
    all_list = OrderItem.objects.all()
    context = {'cart': all_list}
    return render(request, 'l', context)

home/templates/home/cart.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<html>
</br> 
</br>
</br>  
    <body>
                     <!--header part start-->                
 
    <!--header part end-->
     <div class="container mt-5">
        <div class="row pt-5">
          <div class="col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12 mt-3">
                <div class="card">
                  <div class="card-header">
                    <div class="row pt-3 pb-3">
                      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 ">
                        <span style="font-size:20px;font-weight:700;color:grey;color:black">My Cart(3)</span>
                      </div>
                      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12  text-right">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;Deliver to &nbsp;<input type="text" placeholder="user name and address">
                      </div>
                    </div>
                  </div>
                  <div>
                    
                    <div class="card-body">
                      
                      <div class="row pb-3 ">
                        {% for cart_item in cart_items %}
                        <div class="col-xl-4 col-lg-2 col-md-3 col-sm-3 col-12 pt-5 text-center">

                          <img src="{{ cart_item.product.image.url }}" height="200px">
                        
                        </div>
                        
                        <div class="col-xl-8 col-lg-10 col-md-8 col-sm-8 col-12 pt-5">
                          <p>Item Name:&nbsp;{{ cart_item }}</p>
                          <p>quantity:&nbsp;{{ cart_item.quantity}}</p>
                          <p>Price:&nbsp;{{ cart_item.sub_total}} EGP</p>
                          <div class=" col">
                          <div class="input-group input-spinner">                            
                            <div class="input-group-prepend">
                              <a href="{% url 'home:remove_cart' cart_item.product.product_id %}" class="btn btn-light" type="button" id="button-minus"><i class="fa fa-minus"></i></a>
                            </div>
                          <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                            <div class="input-group-prepend">
                              <a href="{% url 'home:add_cart' cart_item.product.product_id %}" class="btn btn-light" type="button" id="button-plus"><i class="fa fa-plus"></i></a>
                            </div>
                          </div>
                        </div>
                          <p><a href="{% url 'home:remove_cart_item' cart_item.product.product_id %}" style="font-weight:700">REMOVE</a></p>
                        </div>
                        {% endfor %}
                      </div>
                      
                      <div class="row">
                        <div class="col pr-5 text-right">
                          <p><button style="text-transform: uppercase;padding:2% 5%;background-color: tomato;color:white;border-color:transparent" data-toggle="collapse" data-target="#collapseTwo,#payment-option"><a href="payment.html" style="color: white;">Place Order</a></button></p>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
          </div>
          <div class="col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12 mt-3 pt-4">
            <div class="container">
              <div class="card">
                <div class="card-header">PRICE DETAILS</div>
                <div class="card-body">
                  <div class="row">
                    <div class="col text-left">
                      Price(3) :
                    </div>
                    <div class="col text-right">
                      &#8377;{{ total }}
                    </div>
                  </div>
                    <div class="row pt-3">
                      <div class="col-7 text-left ">
                        Delivery Charges :
                      </div>
                      <div class="col text-right">
                        Free
                      </div>
                    </div>
                  <hr>
                  <div class="row">
                    <div class="col text-left">
                      Total Amount :
                    </div>
                    <div class="col text-right">
                      &#8377;{{ total }}
                    </div>
                  </div>
                </div> 
              </div>
            </div>
          </div>
      </div>

  </div>
  <!--footer-->
 
     
    </body>
</html>
{% endblock %}

home/templates/home/category_list.html
{% extends 'base.html' %}
{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>+{{categories.count}} Category Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">

                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">

                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for ca in categories%}
                            {% comment %} {% for category_products in ca.category_products.all %}  {% endcomment %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        
                                        <div class="jobs_conetent">
                                            <a href="{% url 'home:category_detail' ca.category_id %}"><h4>{{ca.Name}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                
                                                
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                            {% endfor%}

                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if products.has_previous %}
                                            <li><a href="?page={{ products.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in products.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}
                                        {% if products.has_next %}
                                            <li><a href="?page={{ products.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}

home/templates/home/product_detail.html
{% extends 'base.html' %}
{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{product.Name}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="{{product.image.url}}" alt="" width=50 height=50>
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{product.Name}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{product.Production_country}}</p>
                                        </div>
                                        <div class="location">
                                            <p> Price   {{product.price}}  EGP</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Product description</h4>
                            <p>{{product.description}}.</p>

                        </div>
                        <div class="d-none d-lg-block">
                            <a class="boxed-btn3" href="{% url 'home:add_cart' product.product_id %}">Add to cart</a>
                        </div>

                    </div>

                </div>

                </div>
            </div>
        </div>
    </div>
{% endblock body %}
  

home/templates/home/product_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>+{{all_products.count}} Products Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Search</h3>
                            <form method="GET">
                                {% bootstrap_form product_filter.form%}
                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2">
                            </form>
                        </div>
                    </div>
                </div>                  
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for product in products%}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{{ product.image.url }}" alt="" width=50 height=50>
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'home:product_detail' product.product_id %}"><h4>{{product.Name}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{product.Production_country}}</p>
                                                </div>
                                                <div class="location">
                                                    <p>  {{product.price}} EGP</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a href="job_details.html" class="boxed-btn3">Details</a>
                                        </div>
                  
                                    </div>
                                </div>
                            </div>
                            {% endfor%}

                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if products.has_previous %}
                                            <li><a href="?page={{ products.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in products.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}
                                        {% if products.has_next %}
                                            <li><a href="?page={{ products.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}